### ISSUE TITLE
player.watermark is not a function

### ISSUE THREAD

**Issue by bishnupradhan** [dotsub/videojs-watermark#15]
I am trying to use the videojs-watermark in my player through installing via npm and import the plugin into my typescript and bundle both js via webpack-cli 3.3.
video.js: 7.2.10,
videojs-watermark: 2.0.0

but the error which I am getting is - TypeError: player.watermark is not a function.
Does anybody know what could be wrong or if something is missing in my implementation?

The code  snippets as follows:
```
import videojs from 'video.js';
import 'videojs-watermark';

.......
var player = videojs('my-video');
player.watermark();
player.src({
src: videoUrl,
type: 'video/mp4',
)};
........

```

**Comment by brookslyrette** [comment]
@bishnupradhan this plugin doesn't support `videojs@7.x`. It was designed for 6.x or 5.x.

**Comment by bishnupradhan** [comment]
@brookslyrette the issue has been fixed. 
The plugin needs to register with videojs before calling. That's it.

**Comment by grliao** [comment]
> @brookslyrette the issue has been fixed.
> The plugin needs to register with videojs before calling. That's it.

how to regist the plugin ?
