### ISSUE TITLE
Cannot update to v0.2.0 using NPM

### ISSUE THREAD

**Issue by piotr-cz** [dotsub/videojs-watermark#3]
Somehow 15 days after tagged v0.2.0 release, npm didn't pick it up.

Updating package.json and running npm install says

```
No compatible version found: videojs-watermark@^0.2.0
Valid install targets:
0.1.1, 0.1.0
```

The [NPM page](https://www.npmjs.com/package/videojs-watermark) has latest version v0.1.1

**Comment by brookslyrette** [comment]
Try now

**Comment by piotr-cz** [comment]
Thanks it's working now.
