### ISSUE TITLE
`id` prevents from correct embedding of multiple video players with watermarks on single page

### ISSUE THREAD

**Issue by paluh** [dotsub/videojs-watermark#4]
I want to embed multiple players on one page, but there is an `id` attribute hardcoded for watermark:

https://github.com/dotsub/videojs-watermark/blob/master/src/plugin.js#L24

Do we need this attribute setup?

**Comment by paluh** [comment]
Thanks!

**Comment by lkrnac** [comment]
New version (1.0.0) with this fix is available in NPM.
